export const goodsArray = [
  {
    id: 1,
    img: "https://dull-rose-pawpaw.glitch.me/img/38.jpg",
    title: "Букет из тюльпан Dolche vita (51 шт)",
    dateDelivery: "сегодня в 14:00",
    price: "6700",
  },
  {
    id: 2,
    img: "https://dull-rose-pawpaw.glitch.me/img/39.jpg",
    title: "Букет из роз Grand Avalanche (101 шт)",
    dateDelivery: "сегодня в 14:00",
    price: "14800",
  },
  {
    id: 3,
    img: "https://dull-rose-pawpaw.glitch.me/img/40.jpg",
    title: "Букет из роз Grand Vanilla Cream (101 шт)",
    dateDelivery: "сегодня в 14:00",
    price: "19800",
  },
  {
    id: 4,
    img: "https://dull-rose-pawpaw.glitch.me/img/41.jpg",
    title: "Букет из роз Grand Mirabel (101 шт)",
    dateDelivery: "сегодня в 14:00",
    price: "21300",
  },
  {
    id: 5,
    img: "https://dull-rose-pawpaw.glitch.me/img/42.jpg",
    title: "Букет 101 Эквадорская роза микс",
    dateDelivery: "сегодня в 14:00",
    price: "14200",
  },
  {
    id: 6,
    img: "https://dull-rose-pawpaw.glitch.me/img/43.jpg",
    title: "Букет Mona Lisa (Дельфиниум)",
    dateDelivery: "сегодня в 14:00",
    price: "13600",
  },
  {
    id: 7,
    img: "https://dull-rose-pawpaw.glitch.me/img/1.jpg",
    title: "Авторский букет из роз, диантусов и сухоцветов",
    dateDelivery: "сегодня в 14:00",
    price: "3000",
  },
  {
    id: 8,
    img: "https://dull-rose-pawpaw.glitch.me/img/2.jpg",
    title: "Авторский букет из роз, герберов, диантусов и сухоцветов",
    dateDelivery: "сегодня в 14:00",
    price: "2000",
  },
  {
    id: 9,
    img: "https://dull-rose-pawpaw.glitch.me/img/3.jpg",
    title: "Авторский букет из роз и сухоцветов",
    dateDelivery: "сегодня в 14:00",
    price: "2200",
  },
  {
    id: 10,
    img: "https://dull-rose-pawpaw.glitch.me/img/4.jpg",
    title: "Монобукет из тюльпанов",
    dateDelivery: "сегодня в 14:00",
    price: "1600",
  },
  {
    id: 11,
    img: "https://dull-rose-pawpaw.glitch.me/img/5.jpg",
    title: "Авторский букет из роз и диантусов",
    dateDelivery: "сегодня в 14:00",
    price: "2700",
  },
  {
    id: 12,
    img: "https://dull-rose-pawpaw.glitch.me/img/6.jpg",
    title: "Монобукет из сухоцветов",
    dateDelivery: "сегодня в 14:00",
    price: "1500",
  },
  {
    id: 13,
    img: "https://dull-rose-pawpaw.glitch.me/img/7.jpg",
    title: "Цветы в коробке с лилиями и орхидеями",
    dateDelivery: "сегодня в 14:00",
    price: "3400",
  },
  {
    id: 14,
    img: "https://dull-rose-pawpaw.glitch.me/img/8.jpg",
    title: "Авторский букет из лилий и хризантем",
    dateDelivery: "сегодня в 14:00",
    price: "2900",
  },
  {
    id: 15,
    img: "https://dull-rose-pawpaw.glitch.me/img/9.jpg",
    title: "Монобукет из пионов",
    dateDelivery: "сегодня в 14:00",
    price: "2500",
  },
  {
    id: 16,
    img: "https://dull-rose-pawpaw.glitch.me/img/10.jpg",
    title: "Цветы в корзине с разноцветными ранункулюсами",
    dateDelivery: "сегодня в 14:00",
    price: "3800",
  },
  {
    id: 17,
    img: "https://dull-rose-pawpaw.glitch.me/img/11.jpg",
    title: "Букет из сухоцветов и лаванды",
    dateDelivery: "сегодня в 14:00",
    price: "1700",
  },
  {
    id: 18,
    img: "https://dull-rose-pawpaw.glitch.me/img/12.jpg",
    title: "Цветы в коробке из гербер и ирисов",
    dateDelivery: "сегодня в 14:00",
    price: "3200",
  },
  {
    id: 19,
    img: "https://dull-rose-pawpaw.glitch.me/img/13.jpg",
    title: "Цветы в корзине с миксом весенних цветов",
    dateDelivery: "сегодня в 14:00",
    price: "3600",
  },
  {
    id: 20,
    img: "https://dull-rose-pawpaw.glitch.me/img/14.jpg",
    title: "Монобукет из ромашек",
    dateDelivery: "сегодня в 14:00",
    price: "1400",
  },
  {
    id: 21,
    img: "https://dull-rose-pawpaw.glitch.me/img/15.jpg",
    title: "Авторский букет из гладиолусов и альстромерий",
    dateDelivery: "сегодня в 14:00",
    price: "3100",
  },
  {
    id: 22,
    img: "https://dull-rose-pawpaw.glitch.me/img/16.jpg",
    title: "Букет из сухоцветов с эвкалиптом",
    dateDelivery: "сегодня в 14:00",
    price: "2000",
  },
  {
    id: 23,
    img: "https://dull-rose-pawpaw.glitch.me/img/17.jpg",
    title: "Цветы в коробке с суккулентами и каллами",
    dateDelivery: "сегодня в 14:00",
    price: "3700",
  },
];
